// Mocks generated by Mockito 5.4.4 from annotations
// in zindeai_app/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:zindeai_app/services/models/plan_models.dart' as _i2;
import 'package:zindeai_app/services/models/plan_request.dart' as _i5;
import 'package:zindeai_app/services/plan_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlan_0 extends _i1.SmartFake implements _i2.Plan {
  _FakePlan_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlanService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlanService extends _i1.Mock implements _i3.PlanService {
  MockPlanService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Plan> generatePlan(_i5.GeneratePlanRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #generatePlan,
          [request],
        ),
        returnValue: _i4.Future<_i2.Plan>.value(_FakePlan_0(
          this,
          Invocation.method(
            #generatePlan,
            [request],
          ),
        )),
      ) as _i4.Future<_i2.Plan>);

  @override
  _i4.Future<_i2.Plan> getPlan(String? planId) => (super.noSuchMethod(
        Invocation.method(
          #getPlan,
          [planId],
        ),
        returnValue: _i4.Future<_i2.Plan>.value(_FakePlan_0(
          this,
          Invocation.method(
            #getPlan,
            [planId],
          ),
        )),
      ) as _i4.Future<_i2.Plan>);

  @override
  _i4.Future<void> markMealConsumed(
    String? planId,
    String? mealId,
    bool? isConsumed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMealConsumed,
          [
            planId,
            mealId,
            isConsumed,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
